### PR TITLE
Add Singularity and VM section to prepare

### PR DESCRIPTION
**Pull request by tcooper**

### CODE REVIEW

**Comment by zonca** [comment]
@tcooper a lot of people will have windows machines, could you just demonstrate how to customize an image but have them use a prebuilt image for the hands-on?
Second option would be to provide a single disposable VM and give root to everyone

**Comment by tcooper** [comment]
@zonca I am prepared to demo the Singularity install and bootstrap process which is probably all we'll have time for. Experience with PEARC17 tutorial is that trying to get people running with VirtualBox on Windows is a huge time suck, even WITH a pre-created image.

- Anybody prepared in advance (given the requirements which is why I provided them) should be able to follow along with this part. Perhaps a slight wording change to indicate that VM is required for hands-on of the install / bootstrap / customization steps is enough?
- Anybody NOT prepared will just watch the install/bootstrap demo which is about 3-5 minutes in time on my VM.
- Anybody NOT prepared **CANNOT** customize an image. This step REQUIRES root access on the host used to modify the image.
- Everybody will be able to use Singularity to pull a pre-created image from Singularity Hub and run it interactively and via the Slurm assuming we have reserved resources and training accounts setup.

**Comment by zonca** [comment]
Sure, we have training accounts and will have a reservation.
I think that giving them these instructions before the workshop would be
too cumbersome.
What about making those available inside the folder of your class and point
the most interested students there?
During the class you can just demonstrate that part and mention that
install instructions are available.
Focus more on usage. Also I think most students would be users of
containers maintained by someone more experienced.

**Comment by tcooper** [comment]
@zonca... OK, I'll think about how to include this information without derailing the session while still explaining the power of **controlling your own stack** and how Singularity provides this capability to scientists on HPC systems.

**Pull request closed without merging**
